# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'bropay' do
pod 'Venmo-iOS-SDK', '~>1.3'
end

target 'bropay WatchKit App' do

end

target 'bropay WatchKit Extension' do

end

